apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app.kubernetes.io/name: MyApp # Probably should change
  ports:
    # Ports should be changed probably...
    - protocol: TCP
      port: 8081
      targetPort: 8081
